export {default as Login} from './Login';
export {default as Register} from './Register';
export {default as Home} from './Home';
export {default as Favorites} from './Favorites';
export {default as Playlists} from './Playlists';
export {default as Settings} from './Settings';
export {default as ListenMusic} from './ListenMusic';
export {default as DetailArtist} from './DetailArtist';
export {default as DetailAlbum} from './DetailAlbum';
